# -*- coding: utf-8 -*-
"""Deoldify.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aBz6QhBb5CUkvG3wwiOhvkNNafU8u2hb
"""

# Commented out IPython magic to ensure Python compatibility.
# Clone deoldify Repository
! git clone https://github.com/jantic/DeOldify DeOldify

# change directory to DeOldify Repo
# %cd DeOldify

# For Colab
!pip install -r colab_requirements.txt
!pip install deoldify
# For Local Script
! pip install -r requirements.txt
! pip install fastai==1.0.61
! pip install fastprogress==0.2.7
! pip install torch==1.7.0
! pip install torchvision==0.8.1


# import pytorch library
import torch
# check for GPU
if not torch.cuda.is_available():
    print('GPU not available.')
# necessary imports
import fastai
import PIL

# DeOldify looks for PILLOW_VERSION, which was removed in modern Pillow versions
if not hasattr(PIL, 'PILLOW_VERSION'):
    PIL.PILLOW_VERSION = PIL.__version__

from deoldify.visualize import *
import warnings
warnings.filterwarnings("ignore",
                        category=UserWarning, message=".*?Your .*? set is empty.*?")
# download the artistic model
!mkdir 'models'
!wget https://data.deepai.org/deoldify/ColorizeArtistic_gen.pth -O ./models/ColorizeArtistic_gen.pth

# use the get image colorizer function with artistic model
colorizer = get_image_colorizer(artistic=True)

# Here, we provide the parameters such as source URL, render factor etc.
source_url = 'https://youtube.com/playlist?list=RDU26Xt61-11s&playnext=1&si=-5LbcmsysW_ISpNX' #@param {type:"string"}
render_factor = 21  #@param {type: "slider", min: 7, max: 40}
watermarked = False #@param {type:"boolean"}

if source_url is not None and source_url !='':
    image_path = colorizer.plot_transformed_image_from_url(url=source_url,
          render_factor=render_factor, compare=True, watermarked=watermarked)
    show_image_in_notebook(image_path)
else:
    print('Provide the valid image URL.')