# -*- coding: utf-8 -*-
"""Random numbers using dirichlet

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TNPiBGtAfhN9mwarpFr1O3BmnRsTpjF5
"""

# This is dirichlet in Python, but most languages support the Dirichlet.
import numpy as np

print (np.random.dirichlet(np.ones(12))*100)
sum(np.random.dirichlet(np.ones(12))*100)

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


rng = np.random.default_rng()

s = rng.dirichlet((10, 5, 3), 20)*100
k = s.transpose()

plt.barh(range(20), k[0])

plt.barh(range(20), k[1], left=k[0], color='g')

plt.barh(range(20), k[2], left=k[0]+k[1], color='r')

plt.title("Lengths of Strings")

print (k)

# This is Python, but most languages support the Dirichlet.
# To calculate using random number generation, the average revenue per year for months currently billed free
# Currently out of 12 months, various months are randomly billed free
# At a rate of 1 INR, 2 INR ..... what is the revenue per month



#Random number generation

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

rng = np.random.default_rng()

s = rng.dirichlet((1, 5, 3, 4, 5, 6, 7, 8, 10, 7, 2, 4), 12)*100
k = s.transpose()

plt.barh(range(12), k[0])

plt.barh(range(12), k[1], left=k[0], color='g')

plt.barh(range(12), k[2], left=k[0]+k[1], color='r')

plt.barh(range(12), k[3], left=k[0]+k[1]+k[2], color='m')

plt.barh(range(12), k[4], left=k[0]+k[1]+k[2]+k[3], color='y')

plt.barh(range(12), k[5], left=k[0]+k[1]+k[2]+k[3]+k[4], color='b')

plt.barh(range(12), k[6], left=k[0]+k[1]+k[2]+k[3]+k[4]+k[5], color='g')

plt.barh(range(12), k[7], left=k[0]+k[1]+k[2]+k[3]+k[4]+k[5]+k[6], color='r')

plt.barh(range(12), k[8], left=k[0]+k[1]+k[2]+k[3]+k[4]+k[5]+k[6]+k[7], color='m')

plt.barh(range(12), k[9], left=k[0]+k[1]+k[2]+k[3]+k[4]+k[5]+k[6]+k[7]+k[8], color='y')

plt.barh(range(12), k[10], left=k[0]+k[1]+k[2]+k[3]+k[4]+k[5]+k[6]+k[7]+k[8]+k[9], color='b')

plt.barh(range(12), k[11], left=k[0]+k[1]+k[2]+k[3]+k[4]+k[5]+k[6]+k[7]+k[8]+k[9]+k[10], color='g')

plt.title("Random numbers between 0 to 100 for 12 months")

print (k[0],k[1],k[2],k[3],k[4],k[5],k[6],k[7],k[8],k[9],k[10],k[11])

D = np.tile(np.arange(1, 13), (12, 1))
print(D)

#value from the overall summation

result = np.dot(D,k)

print (result)